:concurrency: 25
:dynamic: true
:limits:
  default: 5
  artist_tags: 1
  profile_mailer: 1
  storage_analysis: 1
  storage_purge: 1
:queues:
  - default
  - artist_tags
  - profile_mailer
  - storage_analysis
  - storage_purge
